Update README.md
* clone over HTTPS instead of SSH (which doesn’t seem to work if you don’t have any keys set up on GitHub)
* remove step 2, the file is already here
* add `--user` switch to the `pip` command. Without this I got:
```
Installing collected packages: Pillow, numpy, Click, stego-lsb
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.8'
Consider using the `--user` option or check the permissions.
```